# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Redshift-OnPrem-Linux
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build adoa image
      inputs:
        command: buildAndPush
        containerRegistry: 'Internal RS-DockerRegistry'
        repository: 'azuredevops-agent'
        dockerfile: './Dockerfile'
        tags: latest
    - task: CmdLine@2
      displayName: Cleaning up images older than 24H
      inputs:
       script: 'docker system prune -a --force --filter "until=24h"' 

    - task: CmdLine@2
      displayName: Cleaning up unneeded images
      inputs:
       script: 'docker system prune -f'