---
apiVersion: apps/v1
kind: Deployment
namespace: azuredevops
metadata:
  name: agent
  labels:
    app.kubernetes.io/name: azure-pipelines-agent
    app.kubernetes.io/instance: agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-pipelines-agent
      app.kubernetes.io/instance: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-pipelines-agent
        app.kubernetes.io/instance: agent
    spec:
      containers:
        - name: azure-pipelines-agent
          image: "awesomejack295/azuredevops-agent:latest"
          imagePullPolicy: Always
          env:
            - name: AZP_AGENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: AZP_URL
              value: "https://dev.azure.com/RedshiftEnt"
            - name: AZP_POOL
              value: rs-03-kub-01
            - name: AZP_TOKEN
              valueFrom: 
                secretKeyRef:
                  key: rs-03-hub-01
                  name: azuredevops-pat